spring.application.name=animeoldies

spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.soukolfgdapjkfrwlxrk
spring.datasource.password=cAv8RhmXGaCwnHxZ

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.generate-dll=true

jwt.secret=animeoldies-clave-secreta-jwt-2026